name: auto build version
on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Fetch RAW value and update README
        run: |
          # Pega o valor da página
          RAW_VALUE=$(curl -s https://msdoors.vercel.app/build)
          
          # Atualiza o README
          sed -i "s/<!-- RAW_VALUE -->.*/<!-- RAW_VALUE -->**${RAW_VALUE}**/" README.md
          
          # Commit se houver mudanças
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --staged --quiet || git commit -m "Update RAW value: ${RAW_VALUE}"
          git push

